# R6

## Exercise 14.2.6 

### Q1. R6 class for bank account {-}

Create the superclass and make sure it works as expected.

```{r, error=TRUE}
library(R6)

# define the needed class
bankAccount <- R6::R6Class(
  "bankAccount",
  public = list(
    # fields -----------------------
    balance = NA,
    name = NA,

    # methods ----------------------
    initialize = function(name = NULL, balance) {
      self$validate(balance)

      self$name <- name
      self$balance <- balance
    },
    deposit = function(amount) {
      self$validate(amount)
      cat("Current balance is: ", self$balance, "\n", sep = "")
      cat("And you are depositing: ", amount)
      self$balance <- self$balance + amount
      invisible(self)
    },
    withdraw = function(amount) {
      self$validate(amount)
      cat("Current balance is: ", self$balance, "\n", sep = "")
      cat("And you are withdrawing: ", amount, "\n", sep = "")
      self$balance <- self$balance - amount
      invisible(self)
    },
    validate = function(amount) {
      stopifnot(is.numeric(amount), amount >= 0)
    },
    print = function() {
      cat("Dear ", self$name, ", your balance is: ", self$balance, sep = "")
      invisible(self)
    }
  )
)

# create an instance of an object
indra <- bankAccount$new(name = "Indra", balance = 100)

indra

# do deposits and withdrawals to see if the balance changes
indra$deposit(20)

indra

indra$withdraw(10)

indra

# make sure input validation checks work
indra$deposit(-20)
indra$deposit("pizza")
indra$withdraw(-54)
Anne <- bankAccount$new(name = "Anne", balance = -45)
```

Create a subclass that errors if you attempt to overdraw

```{r, error=TRUE}
bankAccountStrict <- R6::R6Class(
  "bankAccountStrict",
  inherit = bankAccount,
  public = list(
    withdraw = function(amount) {
      # use method from superclass
      super$withdraw(amount)

      if (self$balance < 0) {
        invisible(self)
        stop(
          cat("\nYou are trying to withdraw more that your balance.\n"),
          cat("I'm sorry, ", self$name, ", I'm afraid I can't do that.", sep = ""),
          call. = FALSE
        )
      }
    }
  )
)

# create an instance of an object
Pritesh <- bankAccountStrict$new(name = "Pritesh", balance = 100)

Pritesh

# do deposits and withdrawals to see if the balance changes
Pritesh$deposit(20)

Pritesh

Pritesh$withdraw(150)

Pritesh

# make sure input validation checks work
Pritesh$deposit(-20)
Pritesh$deposit("pizza")
Pritesh$withdraw(-54)
Pritesh <- bankAccountStrict$new(name = "Pritesh", balance = -45)
```

Create a subclass that charges a fee if overdraw

```{r, error=TRUE}
bankAccountFee <- R6::R6Class(
  "bankAccountFee",
  inherit = bankAccount,
  public = list(
    withdraw = function(amount) {
      # use method from superclass
      super$withdraw(amount)

      if (self$balance < 0) {
        cat("\nI am charging you 10 euros for overdrawing.\n")
        self$balance <- self$balance - 10
        invisible(self)
      }
    }
  )
)

# create an instance of an object
Mangesh <- bankAccountFee$new(name = "Mangesh", balance = 100)

Mangesh

# do deposits and withdrawals to see if the balance changes
Mangesh$deposit(20)

Mangesh

Mangesh$withdraw(150)

Mangesh

# make sure input validation checks work
Mangesh$deposit(-20)
Mangesh$deposit("pizza")
Mangesh$withdraw(-54)
Mangesh <- bankAccountFee$new(name = "Mangesh", balance = -45)
```

### Q2. R6 class for carddeck {-}

```{r, eval=FALSE}
suit <- c("SPADE", "HEARTS", "DIAMOND", "CLUB") # sigh, Windows encoding issues
value <- c("A", 2:10, "J", "Q", "K")
cards <- paste(rep(value, 4), suit)

deck <- R6::R6Class(
  "deck",
  public = list(
    # fields -----------------------


    # methods -----------------------
    draw = function(n) {
      sample(self$cards, n)
    },
    reshuffle = function() {
      sample(self$cards)
      invisible(self)
    },
    print = function() {
      "Drawn cards are:"
      "Number of remaining cards:"
    }
  )
)

# create a new instance of this object
mydeck <- deck$new()

# draw cards
mydeck$draw(4)

# reshuffle
```

## Exercise 14.4.4

Q1. Write R6 class to edit file {-}

```{r}
library(R6)

fileEditor <- R6Class(
  "fileEditor",
  public = list(
    initialize = function(filePath) {
      private$.connection <- file(filePath, open = "wt")
    },
    append_line = function(text) {
      cat(
        text,
        file = private$.connection,
        sep = "\n",
        append = TRUE
      )
    },
    finalize = function() {
      print("Closing the file connection!")
      close(private$.connection)
    }
  ),
  private = list(
    .connection = NULL
  )
)
```

Let's check if it works as expected:

```{r}
f <- tempfile()
myfileEditor <- fileEditor$new(f)

readLines(f)

myfileEditor$append_line("Hi mom!")
myfileEditor$append_line("It's a beautiful day!")

readLines(f)

myfileEditor$finalize()
```

