# Rewriting R code in C++

## Exercise 25.2.6

### Q1. Figure out base function corresponding to Rccp code {-}

```{r}
library(Rcpp)
```


```{r, engine='Rcpp'}
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
double f1(NumericVector x) {
  int n = x.size();
  double y = 0;

  for(int i = 0; i < n; ++i) {
    y += x[i] / n;
  }
  return y;
}

// [[Rcpp::export]]
NumericVector f2(NumericVector x) {
  int n = x.size();
  NumericVector out(n);

  out[0] = x[0];
  for(int i = 1; i < n; ++i) {
    out[i] = out[i - 1] + x[i];
  }
  return out;
}

// [[Rcpp::export]]
bool f3(LogicalVector x) {
  int n = x.size();

  for(int i = 0; i < n; ++i) {
    if (x[i]) return true;
  }
  return false;
}

// [[Rcpp::export]]
int f4(Function pred, List x) {
  int n = x.size();

  for(int i = 0; i < n; ++i) {
    LogicalVector res = pred(x[i]);
    if (res[0]) return i + 1;
  }
  return 0;
}

// [[Rcpp::export]]
NumericVector f5(NumericVector x, NumericVector y) {
  int n = std::max(x.size(), y.size());
  NumericVector x1 = rep_len(x, n);
  NumericVector y1 = rep_len(y, n);

  NumericVector out(n);

  for (int i = 0; i < n; ++i) {
    out[i] = std::min(x1[i], y1[i]);
  }

  return out;
}
```

`f1()` is the same as `mean()`:

```{r}
x <- c(1, 2, 3, 4, 5, 6)

f1(x)
mean(x)
```

`f2()` is the same as `cumsum()`:

```{r}
x <- c(1, 3, 5, 6)

f2(x)
cumsum(x)
```

`f3()` is the same as `any()`:

```{r}
x1 <- c(TRUE, FALSE, FALSE, TRUE)
x2 <- c(FALSE, FALSE)

f3(x1)
any(x1)

f3(x2)
any(x2)
```

`f4()` is the same as `Position()`:

```{r}
x <- list("a", TRUE, "m", 2)

f4(is.numeric, x)
Position(is.numeric, x)
```

`f5()` is the same as `pmin()`:

```{r}
v1 <- c(1, 3, 4, 5, 6, 7)
v2 <- c(1, 2, 7, 2, 8, 1)

f5(v1, v2)
pmin(v1, v2)
```

### Q2. Converting base function to Rcpp {-}

`all()`

```{r, engine='Rcpp'}
// [[Rcpp::export]]
#include <vector>

bool allC(std::vector<bool> x)
{
    int n = x.size();

    for (int i = 0; i < n; i++)
    {
        if (!x[i]) return false;
    }

    return true;
}
```

```{r}
v1 <- rep(TRUE, 10)
v2 <- c(rep(TRUE, 5), rep(FALSE, 5))

all(v1)
allC(v1)

all(v2)
allC(v2)

# performance benefits?
bench::mark(
  all(c(rep(TRUE, 1000), rep(FALSE, 1000))),
  allC(c(rep(TRUE, 1000), rep(FALSE, 1000))),
  iterations = 100
)
```
